# Generated by Django 5.2 on 2025-04-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answervariant',
            unique_together=set(),
        ),
    ]
