# Generated by Django 5.2 on 2025-04-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answervariant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeropen',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='answerpair',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='answervariant',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.questiontype'),
            preserve_default=False,
        ),
    ]
