# Generated by Django 5.2 on 2025-05-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_useranswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='left_part',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='right_part',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='simple_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
