# Generated by Django 5.2 on 2025-05-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_useranswers_left_part_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnswers',
            new_name='UserAnswer',
        ),
    ]
