# Generated by Django 5.2 on 2025-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='percentage_to_pass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(null=True),
        ),
    ]
