# Generated by Django 5.2 on 2025-05-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_result_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='percentage_to_pass',
            field=models.IntegerField(default=80),
            preserve_default=False,
        ),
    ]
