# Generated by Django 5.2 on 2025-05-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_test_percentage_to_pass_alter_test_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='worker',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.result'),
            preserve_default=False,
        ),
    ]
