# Generated by Django 5.2 on 2025-05-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_useranswer_result_useranswer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='TestMembers',
            new_name='TestMember',
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filetype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
