# Generated by Django 5.2 on 2025-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_filetype_rename_testmembers_testmember_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_path',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
