# Generated by Django 5.2 on 2025-05-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_uploadedfile_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='file_path',
            new_name='file',
        ),
    ]
