# Generated by Django 5.2 on 2025-05-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_uploadedfile_file_type_delete_filetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.filetype'),
            preserve_default=False,
        ),
    ]
