# Generated by Django 5.2 on 2025-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('img', 'Фото'), ('mp3', 'Видео')]),
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
    ]
