# Generated by Django 5.2 on 2025-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_worker_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choose_one', 'Выбрать правильный'), ('pairs', 'На соответствие'), ('open_answer', 'Открытый вопрос')]),
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
