# Generated by Django 5.2 on 2025-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_useranswer_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('img', 'Фото'), ('mp4', 'Видео'), ('mp3', 'Аудио')]),
        ),
    ]
