# Generated by Django 5.2 on 2025-06-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_uploadedfile_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_name',
        ),
    ]
