# Generated by Django 5.2 on 2025-06-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_question_question_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='worker',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
