# Generated by Django 5.2 on 2025-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_test_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
