# Generated by Django 5.2 on 2025-06-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_test_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.CharField(blank=True, default='Описание отсутствует', max_length=1000, null=True),
        ),
    ]
