# Generated by Django 5.2 on 2025-06-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_attemptquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='max_tries',
            field=models.IntegerField(default=2, null=True),
        ),
    ]
