# Generated by Django 5.2 on 2025-06-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_test_question_per_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='question_per_attempts',
            new_name='questions_per_attempt',
        ),
    ]
