# Generated by Django 5.2 on 2025-06-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_question_per_attempts_test_questions_per_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='worker',
        ),
    ]
